name: Apply PHP Code Style

on:
  push:
    branches:
      - 'dev'
  pull_request:
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Composer
        run: composer install

      - name: Run PHP Code fixers
        run: composer code:fix

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
