name: "Apply PHP Code Fixers"

on:
  push:
    branches:
      - 'dev'
  pull_request:
    paths:
      - '**.php'

jobs:
  php-code-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: none, curl, dom, fileinfo, iconv, json, mbstring, pdo, phar, redis, simplexml, tokenizer, xml, xmlwriter
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHP Code fixers
        run: composer code:fix

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "bot: apply php code fix changes"
