name: "Lint Code"

on:
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
    # Prevent duplicating jobs on PR-s from local branches
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: sa-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
  cancel-in-progress: true

env:
  APP_ENV: ci

permissions:
  contents: read

jobs:
  coding-guidelines:
    name: PHP Coding Guidelines

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: none, iconv, json, phar, tokenizer, redis
          tools: composer:v2
          coverage: none

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHP Linters
        run: composer code:lint
