name: "Lint Code"

on:
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
    # Prevent duplicating jobs on PR-s from local branches
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"

concurrency:
  group: sa-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
  cancel-in-progress: true

env:
  APP_ENV: ci

permissions:
  contents: read

jobs:
  coding-guidelines:
    name: PHP Coding Guidelines

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: none, curl, dom, fileinfo, iconv, json, mbstring, phar, redis, simplexml, tokenizer, xml, xmlwriter
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run PHP Linters
        run: composer code:lint
